/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class de_holube_batterystatus_jni_PowerEventListener */

#ifndef _Included_de_holube_batterystatus_jni_PowerEventListener
#define _Included_de_holube_batterystatus_jni_PowerEventListener
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     de_holube_batterystatus_jni_PowerEventListener
 * Method:    initPowerEventListener
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_de_holube_batterystatus_jni_PowerEventListener_initPowerEventListener
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
