/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class de_holube_batterystatus_jni_TBatteryPowerLib */

#ifndef _Included_de_holube_batterystatus_jni_TBatteryPowerLib
#define _Included_de_holube_batterystatus_jni_TBatteryPowerLib
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     de_holube_batterystatus_jni_TBatteryPowerLib
 * Method:    initTBatteryPowerLib
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_de_holube_batterystatus_jni_TBatteryPowerLib_initTBatteryPowerLib
  (JNIEnv *, jobject);

/*
 * Class:     de_holube_batterystatus_jni_TBatteryPowerLib
 * Method:    getBatteryPercentage
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_de_holube_batterystatus_jni_TBatteryPowerLib_getBatteryPercentage
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
