name: Build all targets

on:
  workflow_call:
    inputs:
      tag:
        required: true
        type: string
      version:
        required: true
        type: string
      github-release:
        required: false
        type: boolean
        default: false
      prerelease:
        required: false
        type: boolean
        default: true

jobs:
  verify:
    uses: ./.github/workflows/verify.yaml

  build:
    needs: verify
    name: Publish for Windows
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: maven
      - name: Build
        shell: bash
        run: ./build.sh
      - name: Upload Application
        uses: svenstaro/upload-release-action@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: target/battery-status_${{ inputs.version }}.exe
          asset_name: battery-status_${{ inputs.version }}-setup.exe
          prerelease: ${{ inputs.prerelease }}
          overwrite: true
          tag: ${{ inputs.tag }}
          release_name: ${{ inputs.version }}
          body: ""