name: Development Build

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  publish:
    uses: ./.github/workflows/build.yaml
    with:
      tag: dev
      version: "3.3.1"
      github-release: true
      prerelease: true
    secrets: inherit