name: Development Build

on:
  push:
    branches:
      - master
    paths:
      - src/**
      - pom.xml

jobs:
  publish:
    needs: verify
    uses: ./.github/workflows/build.yaml
    with:
      tag: dev
      version: "2.0.0"
      github-release: true
      prerelease: true
    secrets: inherit