name: Development Build

on:
  push:
    branches:
      - master

jobs:
  publish:
    uses: ./.github/workflows/build.yaml
    with:
      tag: dev
      version: "2.3.0"
      github-release: true
      prerelease: true
    secrets: inherit