name: Tagged Release

on:
  push:
    tags:
      - "v*"

jobs:
  create-version-string:
    runs-on: ubuntu-latest
    outputs:
      version: ${{ steps.step1.outputs.test }}
    steps:
      - uses: bhowell2/github-substring-action@1.0.2
        id: step1
        with:
          value: ${{ github.ref_name }}
          index_of_str: "v"
  publish:
    needs: create-version-string
    uses: ./.github/workflows/build.yaml
    with:
      tag: ${{ github.ref_name }}
      version: ${{ needs.create-version-string.outputs.version }}
      github-release: true
      prerelease: true
    secrets: inherit