name: Tagged Release

on:
  push:
    tags:
      - "v*"

jobs:
  publish:
    needs: create-version-string
    uses: ./.github/workflows/build.yaml
    with:
      tag: ${{ github.ref_name }}
      version: ""
      github-release: true
      prerelease: true
    secrets: inherit