name: Tagged Release

on:
  push:
    tags:
      - "v*"

jobs:
  version-job:
    runs-on: ubuntu-latest
    outputs:
      version-string: ${{ steps.step1.outputs.test }}
    steps:
      - id: step1
        run: |
          version=$(echo "${{ github.ref_name }}" | cut -c 2-)
          echo "version=$version" >> "$GITHUB_OUTPUT"

  publish:
    needs: version-job
    uses: ./.github/workflows/build.yaml
    with:
      tag: ${{ github.ref_name }}
      version: ${{needs.version-job.outputs.version-string}}
      github-release: true
      prerelease: true
    secrets: inherit